### ISSUE TITLE
Cannot start control center when using 48 cores 96 threads CPU

### ISSUE THREAD

**Issue by tilsetro** [confluentinc/control-center-images#54]
We recently used docker-compose to set up a confluent Kafka service on a DELL server.
The server utilized 2 Intel(R) Xeon(R) Gold 5318Y CPUs with hyperthreading.
When hyperthreading is enabled, we encountered the following error.
When hyperthreading is disabled, the control center works normally.
Can we set a parameter to avoid the error?

[2022-08-29 06:42:48,084] INFO ClientSelectorManager@7c8c6922{STARTING} requires 48 threads from QueuedThreadPool[qtp581494907]@22a8e87b{STARTED,8<=144<=200,i=0,r=-1,q=0}[ReservedThreadExecutor@564e9c0b{reserved=0/20,pending=0}] (org.eclipse.jetty.util.thread.ThreadPoolBudget)
[2022-08-29 06:42:48,084] WARN unavailable (org.eclipse.jetty.server.handler.ContextHandler.ROOT)
javax.servlet.ServletException: java.lang.IllegalStateException: Insufficient configured threads: required=212 < max=200 for QueuedThreadPool[qtp581494907]@22a8e87b{STARTED,8<=144<=200,i=0,r=-1,q=0}[ReservedThreadExecutor@564e9c0b{reserved=0/20,pending=0}]
        at org.eclipse.jetty.proxy.AbstractProxyServlet.createHttpClient(AbstractProxyServlet.java:350)
        at org.eclipse.jetty.proxy.AbstractProxyServlet.init(AbstractProxyServlet.java:133)
        at javax.servlet.GenericServlet.init(GenericServlet.java:203)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:632)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:415)
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:731)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)

**Comment by khaiirulhafiz** [comment]
You can control by predefining the CPU usage for each container, for ex.

` control-center:
    image: confluentinc/cp-enterprise-control-center:7.7.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker1
      - schema-registry
      - connect
      - ksqldb-server
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: broker1:29092
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_REST_SERVLET_INITIALIZOR_THREAD_POOL_MAX_SIZE: 250
      PORT: 9021
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
`
